### ISSUE TITLE
Skip the Cell Ranger mkfastq steps

### ISSUE THREAD

**Issue by julien-roux** [vibbits/sc_read_kallisto_wrapper#1]
I'm analyzing some 10x genomics dataset but don't have access to the BCL files.

Is there a way to start from the fastq files already produced by `cellranger mkfastq`? How to do this?

**Comment by vibbits** [comment]
Yes, it is possible to do so with small changes in the script. We could provide an adapted version for this purpose. I'll check with my colleague on Monday 29/1 and come back to you.

**Comment by vibbits** [comment]
The issue is solved. We now have an alternative script sc_read_kallisto_simplewrapper.pl. You must put all the fastQ files in the same folder and make sure they respect the naming convention (they should if they have been made by cellranger). I hope this helps.

**Comment by julien-roux** [comment]
Sounds good! Thanks for this, I'll definitely give it a try
